site_name: Docker Service Deploy

docs_dir: 'pages'
site_dir: 'docs'

nav:
- Overview: index.md

- 'Getting Started':
  - 'Install Docker': 'getting-started/install-docker.md'
  - 'Setup Swarm': 'getting-started/setup-swarm.md'

- Commands:
  - Deploy Service: commands/deploy-service.md
  - Expand Service Model: commands/expand-service-model.md
  - Test Auth Config: commands/test-auth-config.md

- 'Service Specification':
  - Basics: service-spec/basics.md

theme:
  name: readthedocs
  highlightjs: true
