site_name: Docker Service Deploy
site_author: flyingpie

docs_dir: 'pages'
site_dir: 'docs'

nav:
- 'Getting Started':
  - 'Install Docker': 'getting-started/01-install-docker.md'
  - 'Setup Swarm': 'getting-started/02-setup-swarm.md'
  - 'Create an Image': 'getting-started/03-create-an-image.md'
  - 'Deploy a Service': 'getting-started/04-deploy-a-service.md'

- Commands:
  - Deploy Service: commands/deploy-service.md
  - Expand Service Model: commands/expand-service-model.md
  - Test Auth Config: commands/test-auth-config.md

- Library:
  - 'Create Service': library/01-create-service.md

- 'Service Specification':
  - Basics: service-spec/basics.md

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  features:
    - navigation.sections
  font: false
  highlightjs: true
  hljs_languages:
    - bash
    - powershell
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  palette:
    scheme: slate
    primary: blue

repo_name: docker-service-deploy
repo_url: http://github.com/flyingpie/docker-service-deploy

extra_javascript:
  - assets/highlight/highlight.pack.js
  - assets/config.js
extra_css:
  - assets/highlight/styles/vs2015.css
  - assets/styles.css

markdown_extensions:
  - sane_lists
  - pymdownx.highlight:
      use_pygments: false